// Auto-generated JNI loader code
// Generated by jni_generator.py
// Found 1 classes with 4 methods

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved)
{
    mosaic::core::LoggerManager::initialize();

    auto helper = mosaic::platform::agdk::JNIHelper::getInstance();

    helper->initialize(vm);

    // Load methods for com/mosaic/engine_bridge/EngineBridge
    {
        auto clazzRef = helper->findClass("com/mosaic/engine_bridge/EngineBridge");
        if (!clazzRef)
        {
            MOSAIC_ERROR("Failed to find EngineBridge class");
            return JNI_ERR;
        }

        helper->createGlobalRef(clazzRef);

        helper->getStaticMethodID("com/mosaic/engine_bridge/EngineBridge", "showQuestionDialog",
                                  "(Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/Boolean;");

        helper->getStaticMethodID("com/mosaic/engine_bridge/EngineBridge", "showInfoDialog",
                                  "(Ljava/lang/String;Ljava/lang/String;)V");

        helper->getStaticMethodID("com/mosaic/engine_bridge/EngineBridge", "showWarningDialog",
                                  "(Ljava/lang/String;Ljava/lang/String;)V");

        helper->getStaticMethodID("com/mosaic/engine_bridge/EngineBridge", "showErrorDialog",
                                  "(Ljava/lang/String;Ljava/lang/String;)V");

    }

    return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM* vm, void* /*reserved*/)
{
    mosaic::platform::agdk::JNIHelper::getInstance()->shutdown();

    mosaic::core::LoggerManager::shutdown();
}
